### ISSUE TITLE
Error when I run the code

### ISSUE THREAD

**Issue by muathalmoslem** [mitre/ACAGPM#4]
Hi,

Thank you for sharing your knowledge and code with the others.

I'm trying to run the code to get the pm2.5 concentration in Arizona. I was able to run the first and second steps of the code. However, when I run the third step, I get the following error message:
`Error in x$.self$finalize(): attempt to apply non-function
`
So I run the same data and code in the script. Again, I got the same error message.
```
Error in x$.self$finalize(): attempt to apply non-function
7.(function (x) 
x$.self$finalize())(<environment>)
6.
.findInheritedMethods(classes, fdef, mtable)
5.
(function (classes, fdef, mtable) 
{
methods <- .findInheritedMethods(classes, fdef, mtable)
if (length(methods) == 1L) ...
4.
cellFromXY(to, xy)
3.
raster::projectRaster(acag, crs = raster::crs(geo))
2.
get_national_geo(st = st, acag = acag)
1.
ACAGPM::pull_state_ACAG(pull_type = "External", level = "State", 
acag = acag, state = c("22", "44", "45"))
```
 I would appreciate it if someone could help me solve this issue
Thank you

**Comment by liberatorea94** [comment]
@muathalmoslem For the sake of reproducing the error, please let me know which ACAG data file you are using from their website, as well as a link. In addition, please send all other code used for steps 1 and 2.

**Comment by muathalmoslem** [comment]
@liberatorea94 

Here is the  data file link: [ https://wustl.app.box.com/v/ACAG-V4NA03-PM25/file/701489095103
](URL).

I haven't changed a lot in the code. I used the example that was provided in the package.
Here is the code: 

`library(raster)
file_dir <- "C:/Users/Muath/Downloads/V4NA03_PM25_NA_200001_200012-RH35-NoNegs.asc"
year <- 2000
acag <- raster::raster(
  file.path(
    file_dir, 
    paste0("V4NA03_PM25_NA_", year, "01_", year, "12-RH35-NoNegs.asc")
  ))
acag@data@names <- "Value"`

Here is the second part of the code 
`state_pm <- ACAGPM::pull_state_ACAG(pull_type = "External", 
                                    level = "State", 
                                    acag = acag, 
                                    state = c("22", "44", "45"))
head(state_pm)`

**Comment by muathalmoslem** [comment]
Hi @liberatorea94,  Did you have a chance to look at the issue? Thank you

**Comment by liberatorea94** [comment]
Hello @muathalmoslem , I am reviewing this issue now. I do appear to be having a similar issue, I will get you an update by the end of today.

**Comment by liberatorea94** [comment]
@muathalmoslem Following up on my last comment - we have found a solution to the issue, which had to do with projecting the raster file to the tigris shapefiles' coordinate reference system. I will notify you when the changes have been pushed to main.
